image: python:3.8

stages:
  - build
  - test

before_script:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt

build:
  stage: build
  script:
    - echo "Building the application"

test:
  stage: test
  script:
    - pytest
    - black --check app/ tests/
    - flake8 app/ tests/
